name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: estimate-test
      id: estimate-test
      uses: education/autograding-command-grader@v1
      with:
        test-name: estimate-test
        setup-command: npm install
        command: npx jest estimate.test.js
        timeout: 10
        max-score: 33
    - name: integrate-test
      id: integrate-test
      uses: education/autograding-command-grader@v1
      with:
        test-name: integrate-test
        setup-command: npm install
        command: npx jest integrate.test.js
        timeout: 1
        max-score: 33
    - name: outlier-test
      id: outlier-test
      uses: education/autograding-command-grader@v1
      with:
        test-name: outlier-test
        setup-command: npm install
        command: npx jest outlier.test.js
        timeout: 1
        max-score: 34
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        ESTIMATE-TEST_RESULTS: "${{steps.estimate-test.outputs.result}}"
        INTEGRATE-TEST_RESULTS: "${{steps.integrate-test.outputs.result}}"
        OUTLIER-TEST_RESULTS: "${{steps.outlier-test.outputs.result}}"
      with:
        runners: estimate-test,integrate-test,outlier-test
